# Generated by Django 2.1.2 on 2018-10-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('resumo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
