# Generated by Django 2.1.2 on 2018-10-29 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado'), (7, 'Domingo')], unique=True)),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
            ],
            options={
                'ordering': ('dia_da_semana',),
            },
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('praca', models.CharField(max_length=50)),
                ('estacao', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='programa',
            name='participacao',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='url_streaming',
            field=models.CharField(default='http://radio/streaming/content', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='url_thumb',
            field=models.CharField(default='http://radio/thumb/pic.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radio',
            name='programas',
            field=models.ManyToManyField(to='core.Programa'),
        ),
        migrations.AddField(
            model_name='programa',
            name='programacoes',
            field=models.ManyToManyField(to='core.HorarioFuncionamento'),
        ),
    ]
