# Generated by Django 2.1.2 on 2018-10-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181029_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='url_streaming',
        ),
        migrations.AddField(
            model_name='radio',
            name='url_streaming',
            field=models.CharField(default='uri', max_length=255),
            preserve_default=False,
        ),
    ]
