# Generated by Django 2.1.2 on 2018-10-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_programa_prioridade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariofuncionamento',
            options={},
        ),
    ]
